### PR TITLE
Unit testing infrastructure

### PR DESCRIPTION
**Pull request by itowlson**
Due to the limited safety features of JavaScript and the complex flows of the extension, it is not always easy to have confidence that one hasn't broken anything during maintenance.  This PR does not change any functionality, but modularises components and injects them in a way which facilitates automated testing.  As an initial step, it also adds automated tests for kubectl detection and invocation.

As an additional safety feature, some code is converted from callback style or explicit promise construction to use TypeScript async/await.  There are also some linting and debugging fixes.

### CODE REVIEW

**Comment by bnookala** [comment]
I noted that you're using a lot of fake response objects/wrapper functions. What do you think of using Sinon.JS for mocking and stubbing vscode and node functionality? http://sinonjs.org/

**Comment by brendandburns** [comment]
@itowlson what are your thoughts on Simon.js?  I haven't used it myself....

**Comment by itowlson** [comment]
@bnookala @brendandburns I'm not familiar with Sinon.JS.  It certainly looks like it would help, but I have a bad habit of writing my own fakes after bad experiences with mocking libraries in the C# world!  My inclination would be to merge this as it stands (once I rebase it), and then tackle refactoring around a library as a separate PR so we can see if it looks clearer and how well it works.  Does that seem a reasonable approach to both of you, or would you prefer to keep the history clean?

**Comment by itowlson** [comment]
Rebased onto master

**Comment by brendandburns** [comment]
Thanks!

**Pull request merged**
