### PR TITLE
Typescript cleanup, add tslint.json + add typescript linter

### PR DESCRIPTION
**Pull request by bnookala**
Since we've moved to typescript, eslint won't actually work anymore. Thankfully, there's tslint!

I've added a tslint config here. In addition, I'd recommend adding the tslint extension to VS Code as it automatically runs tslint on file changes: https://marketplace.visualstudio.com/items?itemName=eg2.tslint

### CODE REVIEW

**Comment by brendandburns** [comment]
Ugh, sorry, just merged some @itowlson changes, so this needs a rebase.

Thanks!
--brendan

**Comment by brendandburns** [comment]
@bnookala would love to merge this, but there are some conflicts that need to be resolved.

**Comment by bnookala** [comment]
Sorry! Forgot about this, I'll take a look at the conflicts today :)

**Comment by bnookala** [comment]
@brendandburns Sorry this took so long - had to be in Redmond last week, and was occupied with other work. Rebased, and tested, and everything seems to be working.

**Pull request merged**
