### PR TITLE
Convert to typescript

### PR DESCRIPTION
**Pull request by bnookala**
Most of this is still just vanilla javascript, actually - but the file format has been changed to `.ts`, making it typescript friendly. As an initial feature, I changed the imports from using `require` to using `import * as blah from 'foo'` and started making use of the `export` syntax. I built this work upon https://github.com/brendandburns/vs-kubernetes/pull/14, which hasn't been merged yet. For a cleaner looking diff, please merge that first, and then I can rebase + push again.

### CODE REVIEW

**Comment by brendandburns** [comment]
Needs rebase, then we can merge this asap.

Thanks!

**Comment by bnookala** [comment]
@brendandburns @itowlson rebased on master :)

**Comment by brendandburns** [comment]
LGTM. merging.

**Comment by itowlson** [comment]
Nice!

**Pull request merged**
